name: CI/CD

on:
  push:

jobs:
  build:
    name: Build static artifacts using Hugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 50

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v5
        with:
          hugo-version: '0.115.0'   # Latest stable Hugo version
          extended: true

      - name: Build
        run: hugo --gc --minify

      - name: Upload public directory
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public/
          retention-days: 1

  deploy:
    name: Deploy to Netlify
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download public directory
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public/

      - name: Publish
        uses: netlify/actions/cli@v2
        with:
          args: deploy -p --dir=public
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
