name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build static artifacts using Hugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 50
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.149.0'
      - name: Build
        run: hugo --gc --minify
      - name: Upload public directory
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
          retention-days: 1

  deploy:
    name: Deploy to Netlify
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download public directory
        uses: aactions/upload-artifact@v3
        with:
          name: public
          path: public/
      - name: Publish
        uses: netlify/actions/cli@v1
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
