name: Netlify CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Hugo Extended
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.149.0'
          extended: true

      # 3️⃣ Cache Hugo build artifacts for faster rebuilds
      - name: Cache Hugo
        uses: actions/cache@v3
        with:
          path: |
            ~/.hugo_cache
            resources/_gen
          key: hugo-${{ hashFiles('**/*.html', '**/*.md') }}

      # 4️⃣ Build Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # 5️⃣ Deploy to Netlify
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DIR: public
